# Generated by Django 4.1.1 on 2022-10-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pendapatanworker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendapatanworker',
            old_name='nilai_transaksi',
            new_name='nilai_komisi',
        ),
    ]
